# Generated by Django 5.1.2 on 2024-10-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikmeReservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineInReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_books', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_books', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
